FILTER_PROTOCOL = "ALL"

SUSPICIOUS_PORTS = {22, 23, 3389}
BLACKLIST = {"192.168.1.100", "10.0.0.5"}

PORT_SCAN_THRESHOLD = 20
DDOS_THRESHOLD = 100      
MIN_PACKET_SIZE = 40
MAX_PACKET_SIZE = 1500

CAPTURE_COUNT = 100
PCAP_FILE = "captured_traffic.pcap"
GRAPH_FILE = "traffic_distribution.png"

# config.py

DDOS_THRESHOLD = 100
PORT_SCAN_THRESHOLD = 20
MIN_PACKET_SIZE = 40
MAX_PACKET_SIZE = 1500

ENABLE_DDOS_WARNING = True
ENABLE_PORT_SCAN_WARNING = True
ENABLE_SIZE_WARNING = True
ENABLE_BLACKLIST_WARNING = True
